disabled = false
languageCode = "fr"
languageName = "Francais"
weight = 2
title = "Robin Nicole"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Robin Nicole"

[params.author]
  name = "Robin (comme \"Robin des Bois\")"
  image = "img/blowfish_logo.png"
  imageQuality = 96
  headline = "ML & AI (the talles engineer in the room)"
  bio = "Resolveur de problemes depuis 2013"
  links = [
#     { email = "mailto:your-email@example.com" },
    { github = "https://github.com/robinicole" },
    { ko-fi = "https://buymeacoffee.com/robin_lance_gratuite" },
    { linkedin = "https://www.linkedin.com/in/robin-nicole-phd-54929349/" },
  ]
