# -- Menu principal --

[[main]]
  name = "Travailler avec moi"
  url = "https://withrobin.space/fr"
  weight = 5

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

# -- Menu pied de page --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
